Repository kiwix/kiwix-js, pull requests merged in 2020-11, with the labels that each got.

#658 Add a low level block cache
  www/js/lib/filecache.js
  www/js/lib/util.js
  www/js/lib/zimfile.js
Labels: enhancement

#668 Exempt articleId assignment from Active Content Warning
  www/js/app.js
Labels: bug

#669 Update README.md
  README.md
Labels: information

#670 Add WebP Polyfills in jQuery mode
  tests/init.js
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/uiUtil.js
  www/js/lib/webpHeroBundle_0.0.0-dev.27.js
  www/js/lib/webpHeroPolyfills_0.0.0-dev.27.js
Labels: enhancement

#676 tests: Remove redundant xzdec.js include
  tests.html
Labels: cleanup

#677 Extract images sequentially in jQuery mode
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement
