Repository kiwix/kiwix-js, pull requests merged in 2020-07, with the labels that each got.

#630 Do not assume urlPtrPos is just after mimeList when reading it
  www/js/lib/zimfile.js
Labels: bug

#635 Updated cookie to ensure samesite is set as Strict.
  www/js/lib/settingsStore.js
Labels: enhancement

#634 Update CHANGELOG for v2.8.0
  CHANGELOG.md
Labels: information

#640 Make Privacy Policy publicly accessible
  PRIVACY_POLICY.md
Labels: information
