Repository kiwix/kiwix-js, pull requests merged in 2022-02, with the labels that each got.

#805 Update changelog for v3.3.0
  CHANGELOG.md
Labels: documentation

#822 Fix race condition while loading decompressors
  www/js/app.js
  www/js/lib/uiUtil.js
  www/js/lib/xzdec_wrapper.js
  www/js/lib/zstddec_wrapper.js
Labels: bug, regression

#829 Fix errors in publish extension workflow and add logging
  .github/workflows/publish-extension.yaml
  scripts/rewrite_app_version_number.sh
Labels: bug, tests, build

#830 Changelog for v3.3.1
  CHANGELOG.md
Labels: build

#804 Added bootstrap modal for alert and confirm popups:WIP #798
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/lib/settingsStore.js
  www/js/lib/uiUtil.js
  www/js/lib/zimArchive.js
  www/js/lib/zimArchiveLoader.js
Labels: enhancement, user interface

#793 Auto Dark mode Theme added
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement, user interface

#838 Upgrade webp-hero library and reuse the canvas
  scripts/Check-OfflineFilesList.ps1
  tests/init.js
  www/css/kiwixJS_invert.css
  www/css/kiwixJS_mwInvert.css
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/uiUtil.js
  www/js/lib/util.js
  www/js/lib/webpHeroBundle_0.0.0-dev.27.js
  www/js/lib/webpHeroBundle_0.0.2.js
Labels: not-main-usage, dependencies
