Repository kiwix/kiwix-js, pull requests merged in 2022-12, with the labels that each got.

#902 Removed most usage of innerHTML
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: cleanup, user interface

#941 Initiate full-text search earlier
  www/js/lib/zimArchive.js
Labels: enhancement, backend

#944 Update documentation of full text search
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement, information, documentation
