Repository kiwix/kiwix-js, pull requests merged in 2022-11, with the labels that each got.

#911 Changelog for v3.6.0
  CHANGELOG.md
  manifest.json
  service-worker.js
  www/js/app.js
Labels: build

#917 Replace jQuery for hide and show statements selected by ID
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: cleanup, remove-jquery

#923 Exempt more latex images from re-inversion in dark mode
  www/css/kiwixJS_mwInvert.css
Labels: user interface

#925 Replace `.click()`, `.focus()` and `.attr()` jQuery functions with equivalent native JS
  www/js/app.js
Labels: cleanup, remove-jquery

#932 Add fulltext directory listing to archive metadata
  www/js/lib/zimArchive.js
  www/js/lib/zimfile.js
Labels: backend
