Repository kiwix/kiwix-js, pull requests merged in 2022-01, with the labels that each got.

#779 Added tooltips to icons and settings.
  www/index.html
Labels: user interface

#774 Check offline files list through CI
  .github/workflows/CI.yml
  scripts/Check-OfflineFilesList.ps1
Labels: tests

#796 Revert check for PWA existence prior to passthrough
  www/js/app.js
Labels: regression

#792 Update documentation to include new implementation
  README.md
Labels: documentation

#800 Added CONTRIBUTING.md : WIP
  CONTRIBUTING.md
  README.md
Labels: documentation

#797 Provide methods for resetting the app and bypassing appCache
  service-worker.js
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/lib/settingsStore.js
  www/js/lib/uiUtil.js
Labels: enhancement, tests, user interface

#803 Copy CODE_OF_CONDUCT and REPORT_BUG from kiwix/overview
  CODE_OF_CONDUCT.md
  README.md
  REPORT_BUG.md
Labels: documentation

#811 Deal correctly with favicon
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: bug

#809 Default to SW mode when accessing app as PWA
  www/js/app.js
Labels: enhancement

#807 Fix incorrect processing of titles with question marks and anchor parameters
  service-worker.js
  tests/tests.js
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: bug
