Repository kiwix/kiwix-js, pull requests merged in 2023-03, with the labels that each got.

#971 Added `http-server` script
  CONTRIBUTING.md
  package.json
Labels: dependencies, tests, build

#976 Add sandbox to iframe
  service-worker.js
  www/index.html
  www/js/app.js
Labels: bug, security

#978 Fix missing full text search cancellation
  www/js/lib/zimArchive.js
Labels: bug, user interface

#968 Removed usage of jquery while opening and closing bootstrap modals
  www/index.html
  www/js/lib/uiUtil.js
Labels: user interface, remove-jquery
