Repository kiwix/kiwix-js, pull requests merged in 2023-08, with the labels that each got.

#1039 Add end-to-end tests with Selenium
  .github/workflows/CI.yml
  package-lock.json
  package.json
  tests/chromium.e2e.runner.js
  tests/firefox.e2e.runner.js
  tests/ieMode.e2e.runner.js
  tests/kiwix-js.e2e.spec.js
  tests/microsoftEdge.e2e.runner.js
  www/index.html
Labels: tests, build, user interface

#1044 Add more explicit tests for ServiceWorker compatibility
  .github/workflows/CI.yml
  tests/ieMode.e2e.runner.js
  tests/kiwix-js.e2e.spec.js
Labels: tests, build, user interface

#1046 Add documentation and licensing for e2e tests
  CONTRIBUTING.md
  TESTS.md
  tests/chromium.e2e.runner.js
  tests/firefox.e2e.runner.js
  tests/ieMode.e2e.runner.js
  tests/legacy-ray_charles.e2e.spec.js
  tests/microsoftEdge.e2e.runner.js
  www/index.html
Labels: documentation, tests

#1047 Set up e2e tests on BrowserStack
  .github/workflows/CI.yml
  tests/chrome58.bs.runner.js
  tests/edge18.bs.runner.js
  tests/firefox56.bs.runner.js
  tests/firefox61.bs.runner.js
  tests/legacy-ray_charles.e2e.spec.js
  tests/safari14.bs.runner.js
  www/js/app.js
Labels: tests, build, user interface

#1052 Exempt BrowserStack tests for PRs from forked Repos
  .github/workflows/CI.yml
Labels: tests, build

#1054 Update documentation on tests for BrowserStack
  CONTRIBUTING.md
  TESTS.md
Labels: documentation, tests

#1055 Attempt to force failure if one test fails with PowerShell in GitHub Actions
  .github/workflows/CI.yml
Labels: bug, tests

#1059 Fix legacy test for IE mode
  tests/legacy-ray_charles.e2e.spec.js
Labels: bug, build

#1061 Add internationalization framework
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  package-lock.json
  package.json
  rollup.config.js
  service-worker.js
  tests/gutenberg_ro.e2e.spec.js
  tests/legacy-ray_charles.e2e.spec.js
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/lib/translateUI.js
  www/js/lib/uiUtil.js
  www/js/lib/util.js
  www/js/lib/zimArchive.js
Labels: enhancement, user interface, accessibility, i18n

#1067 Translation cleanup and UI touches
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  manifest.json
  manifest.v2.json
  manifest.webapp
  service-worker.js
  ubuntu_touch/manifest.json
  www/index.html
  www/js/app.js
Labels: user interface, accessibility, i18n

#1057 Moved configuration code to init.js
  scripts/test_duplicate_values.sh
  scripts/test_pwa_server.sh
  www/js/app.js
  www/js/init.js
Labels: cleanup, backend, task

#1075 Update codeql-analysis.yml to CodeQL v2
  .github/workflows/codeql-analysis.yml
Labels: build

#1080 Temporarily remove i18next but leave instructions to reactivate
  package-lock.json
  package.json
  scripts/gitignore.patch
  www/js/lib/translateUI.js
Labels: dependencies, i18n

#1082 Update build scripts to use version from init.js
  .github/workflows/CI.yml
  scripts/Publish-Implementation.ps1
  scripts/Set-AppVersion.ps1
  scripts/create_all_packages.sh
  scripts/rewrite_app_version_number.sh
Labels: build, task

#1084 Fix corrupt gitignore patch
  .github/workflows/CI.yml
  ADDING_DEPENDENCIES_NODE_MODULES.md
  scripts/gitignore.patch
Labels: bug, build

#1078 Review French translations and propagate changes to other languages
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  scripts/Check-OfflineFilesList.ps1
  service-worker.js
  www/index.html
  www/js/app.js
  www/js/lib/translateUI.js
  www/js/lib/uiUtil.js
Labels: user interface, accessibility, i18n

#1089 Restore IE Mode e2e testing in Windows
  .github/workflows/CI.yml
Labels: regression, tests, build

#1086 Launching the vite server will always open the app with appCache=false
  vite.config.js
Labels: enhancement, build
