Repository kiwix/kiwix-js, pull requests merged in 2023-12, with the labels that each got.

#1173 Work towards warc2zim reading
  babel.config.js
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  manifest.fx.v3.json
  manifest.json
  manifest.v2.json
  manifest.webapp
  package-lock.json
  package.json
  replayWorker.js
  rollup.config.js
  service-worker.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  ubuntu_touch/manifest.json
  www/article.html
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/cache.js
  www/js/lib/settingsStore.js
  www/js/lib/uiUtil.js
  www/js/lib/zimArchive.js
  www/topFrame.html
Labels: dependencies, backend, zimit

#1176 Fix opening of new Zimit tabs to local articles and PDFs
  www/js/app.js
Labels: zimit

#1179 Fix failure to handle PDFs in openzim archive types
  README.md
  www/js/app.js
Labels: bug, regression, security, user interface

#1180 Fix missing webmanifest
  docker/dockerfile-browser-extension.pwa
  rollup.config.js
  service-worker.js
  www/js/lib/zimArchiveLoader.js
Labels: build, bug-non-critical

#1181 Refactor zimit processing
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  www/js/app.js
  www/js/lib/uiUtil.js
  www/js/lib/zimArchive.js
Labels: cleanup, dependencies, zimit

#1185 replaced localStorage with settingsStore method
  www/js/app.js
  www/js/lib/abstractFilesystemAccess.js
Labels: good first issue, cleanup
