Repository kiwix/kiwix-js, pull requests merged in 2023-09, with the labels that each got.

#1091 Fix file picking in latest Chromium browsers for Android
  www/index.html
Labels: not-main-usage, regression, user interface

#1092 Use faster & more compatible method to load lang object
  i18n/en.jsonp
  i18n/es.jsonp
  i18n/fr.jsonp
  service-worker.js
  www/js/app.js
  www/js/lib/translateUI.js
  www/js/lib/util.js
Labels: user interface, accessibility, i18n

#1093 Documentation updates
  README.md
  TESTS.md
  backgroundscript.js
  images/electron-color.svg
  images/microsoftwindows-color.svg
  images/ubuntu-color.png
  service-worker.js
  tests/index.html
  tests/init.js
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/abstractFilesystemAccess.js
  www/js/lib/filecache.js
  www/js/lib/translateUI.js
  www/js/lib/uiUtil.js
  www/js/lib/utf8.js
  www/js/lib/util.js
  www/js/lib/xzdec_wrapper.js
  www/js/lib/zimArchive.js
  www/js/lib/zimArchiveLoader.js
  www/js/lib/zimDirEntry.js
  www/js/lib/zimfile.js
  www/js/lib/zstddec_wrapper.js
Labels: information, documentation

#1100 Ensure dockerfile serves jsonp with correct MIME type
  docker/dockerfile-browser-extension.pwa
Labels: build, bug-non-critical

#1106 Fix active content warning for PhET ZIMs
  www/js/app.js
Labels: regression, extensions, bug-non-critical

#1095 Update CHANGELOG.md
  CHANGELOG.md
Labels: information, documentation, build

#1110 Add missing i18n folder to dockerfile
  docker/dockerfile-browser-extension.pwa
Labels: bug, dependencies, build, extensions, i18n

#1113 Completely exit local code on comms with remote
  www/js/app.js
  www/js/init.js
Labels: bug, regression, extensions

#1115 Ensure packages contain i18n files
  scripts/create_all_packages.sh
  scripts/package_chrome_extension.sh
  scripts/package_firefox_extension.sh
  scripts/package_firefoxos_app.sh
Labels: bug, build, i18n

#1117 Rename jsonp files to js so they can be accessed by extensions
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  service-worker.js
  www/js/lib/translateUI.js
Labels: bug, build, extensions, i18n

#1121 Switch to Manifest V3 for Firefox
  backgroundscript.js
  manifest.fx.v3.json
  rollup.config.js
  scripts/create_all_packages.sh
  scripts/package_firefox_extension.sh
Labels: build, extensions

#1123 Launch spinner as soon as possible
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/js/app.js
Labels: enhancement, user interface

#1102 Transition animation cleanup and page animation turned off by default
  www/js/app.js
  www/js/init.js
  www/js/lib/uiUtil.js
Labels: cleanup, user interface
