Repository kiwix/kiwix-js, pull requests merged in 2023-11, with the labels that each got.

#1131 [ADD] Native File System support to reload zim file
  .gitignore
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  service-worker.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/abstractFilesystemAccess.js
  www/js/lib/cache.js
  www/js/lib/zimfile.js
Labels: enhancement, backend

#1148 Fix some UI spacing issues
  www/css/app.css
  www/index.html
Labels: user interface

#1149 Complete translation of fxos UI elements
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/js/lib/zimArchive.js
  www/js/lib/zimArchiveLoader.js
Labels: user interface, i18n

#1153 Enable tab access to file, folder and library selectors
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement, user interface, accessibility

#1145 Update CHANGELOG for v3.11.0
  CHANGELOG.md
Labels: information

#1155 Translation corrections and add tool tip explaining library
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
Labels: user interface, i18n

#1158 Make a generic browserAction for backgroundscript
  backgroundscript.js
Labels: tests, accessibility, extensions

#1161 Fix some ESLint rules (indentation)
  www/js/app.js
  www/js/lib/arrayFromPolyfill.js
  www/js/lib/filecache.js
  www/js/lib/settingsStore.js
  www/js/lib/utf8.js
  www/js/lib/util.js
  www/js/lib/xzdec_wrapper.js
  www/js/lib/zstddec_wrapper.js
Labels: cleanup

#1162 Fix scrolling of search results
  CHANGELOG.md
  www/js/app.js
Labels: user interface, accessibility, bug-non-critical

#1165 Fix some anomalies in tests
  .github/workflows/CI.yml
  tests/e2e/runners/chrome/chrome60.bs.runner.js
  tests/e2e/runners/firefox/firefox70.bs.runner.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
Labels: cleanup, tests

#1167 Fix zim file.name property when remote testing and improve test formatting
  .github/workflows/CI.yml
  tests/e2e/runners/chrome/chrome58.bs.runner.js
  tests/e2e/runners/chrome/chrome60.bs.runner.js
  tests/e2e/runners/chrome/chromium.e2e.runner.js
  tests/e2e/runners/edge/ieMode.e2e.runner.js
  tests/e2e/runners/edge/microsoftEdge.e2e.runner.js
  tests/e2e/runners/firefox/firefox.e2e.runner.js
  tests/e2e/runners/firefox/firefox56.bs.runner.js
  tests/e2e/runners/firefox/firefox70.bs.runner.js
  tests/e2e/runners/safari/safari14.bs.runner.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  www/js/lib/zimfile.js
Labels: bug, backend, tests

#1164 Remove unnecessary initOrKeepAliveServiceWorker
  .github/workflows/CI.yml
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  service-worker.js
  tests/e2e/runners/chrome/chrome60.bs.runner.js
  tests/e2e/runners/edge/ieMode.e2e.runner.js
  tests/e2e/runners/firefox/firefox70.bs.runner.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  www/js/app.js
  www/js/lib/abstractFilesystemAccess.js
Labels: enhancement, cleanup, backend

#1168 Update rollup to v4
  package-lock.json
  package.json
Labels: dependencies, build

#1163 Add rudimentary static Zimit support
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/js/app.js
  www/js/lib/zimArchive.js
Labels: enhancement, not-main-usage, backend, zimit

#1169 Avoid side effects when loading archive
  tests/unit/index.html
  www/js/lib/cache.js
  www/js/lib/zimArchive.js
Labels: cleanup, backend

#1170 Fix anomalous boot loop when app is in jQuery mode and no SW is registered
  www/js/app.js
Labels: bug
