Repository kiwix/kiwix-js, pull requests merged in 2024-01, with the labels that each got.

#1160 Use libzim for reading ZIM contents
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/zimArchive.js
Labels: enhancement, dependencies, backend

#1196 Warn instead of throwing if `minorVersion` > 2
  www/js/lib/zimArchive.js
Labels: regression, backend, bug-non-critical

#1200 Add a way to detect that an archive is zimit2
  www/js/lib/zimArchive.js
Labels: enhancement, backend, zimit

#1201 Open external links and PDFs outsde zimit sandbox
  www/js/app.js
  www/js/lib/uiUtil.js
  www/js/lib/zimArchive.js
Labels: bug, backend, zimit
