Repository kiwix/kiwix-js, pull requests merged in 2024-03, with the labels that each got.

#1219 Fix errors enumerating ZIM archives in directory
  www/js/app.js
  www/js/lib/abstractFilesystemAccess.js
Labels: cleanup, backend

#1221 Reopen last selected archive with File System Access API
  README.md
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/abstractFilesystemAccess.js
Labels: enhancement, backend, user interface

#1215 changed jquery to safe mode in UI
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: user interface

#1224 Do not display File Selectors before jumping to remote
  www/js/app.js
Labels: user interface, extensions, bug-non-critical

#1227 update regex to match PhET
  www/js/app.js
Labels: regression, bug-non-critical

#1226 Rewrite README intro
  README.md
Labels: information, documentation

#1228 Fix duplicate credits in about section
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
Labels: information, documentation

#1225 Remove remaining JQuery
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: cleanup, dependencies, remove-jquery

#1236 Add option to turn off external link warning
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
  www/js/app.js
  www/js/init.js
  www/js/lib/uiUtil.js
Labels: user interface, accessibility

#1238 Change method for patching gitignore
  .github/workflows/CI.yml
  .github/workflows/publish-extension.yaml
  .gitignore
  ADDING_DEPENDENCIES_NODE_MODULES.md
  scripts/gitignore.patch
  scripts/patch_gitignore.sh
Labels: information, dependencies, tests, build

#1237 Fix bug for empty search box on initial ZIM load
  www/js/app.js
Labels: user interface, accessibility, bug-non-critical
