Repository kiwix/kiwix-js, pull requests merged in 2024-05, with the labels that each got.

#1230 Workaround for over-encoded URLs in zimit2
  www/js/app.js
Labels: bug, backend, zimit

#1245 Non-file Dragging Bug Fix
  www/css/app.css
  www/js/app.js
Labels: user interface, accessibility, bug-non-critical

#1250 Added ZIM metadata to security dialogue box when opening ZIM for the first time
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/css/app.css
  www/js/app.js
  www/js/lib/zimArchive.js
Labels: security, user interface
