Repository kiwix/kiwix-js, pull requests merged in 2024-02, with the labels that each got.

#1207 Deal with zimit2 URL handling in jQuery mode
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: backend, user interface, zimit

#1208 Fix deprecated actions/checkout
  .github/workflows/CI.yml
  .github/workflows/Release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-extension.yaml
Labels: backend, tests, build

#1209 Add content warning for zimit2 in service worker local mode
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: user interface, accessibility, extensions, zimit

#1192 Added a feature that prompts a user when a new Zim file is opened.
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  tests/unit/js/init.js
  www/index.html
  www/js/app.js
  www/js/init.js
Labels: security, user interface

#1211 CHANGELOG for v4.0
  CHANGELOG.md
  README.md
Labels: information
