Repository kiwix/kiwix-js, pull requests merged in 2025-06, with the labels that each got.

#1320 Added Wikipedia's own Dark Mode solution
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  service-worker.js
  www/css/app.css
  www/css/kiwixJS_wikiVector.css
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement, user interface

#1306 feat: added toc dropup like in Kiwix-PWA
  www/css/app.css
  www/index.html
  www/js/app.js
  www/js/lib/uiUtil.js
Labels: enhancement, user interface, accessibility

#1341 Update CHANGELOG for v4.2.0
  CHANGELOG.md
Labels: information, build, task

#1354 Update Ubuntu Touch sdk to 20.04
  .github/workflows/Release.yml
  scripts/package_ubuntu_touch_app.sh
  scripts/ubuntu_touch_packages/click-reviewers-tools_0.44_16.04.1_all.deb
  scripts/ubuntu_touch_packages/click_0.4.43+16.04.20170613-0ubuntu1_amd64.deb
  scripts/ubuntu_touch_packages/gir1.2-click-0.4_0.4.43+16.04.20170613-0ubuntu1_amd64.deb
  scripts/ubuntu_touch_packages/libclick-0.4-0_0.4.43+16.04.20170613-0ubuntu1_amd64.deb
  scripts/ubuntu_touch_packages/python3-click-package_0.4.43+16.04.20170613-0ubuntu1_amd64.deb
  ubuntu_touch/clickable.yaml
  ubuntu_touch/kiwix.apparmor
  ubuntu_touch/manifest.json
Labels: not-main-usage, dependencies, build
