Repository kiwix/kiwix-js, pull requests merged in 2025-03, with the labels that each got.

#1319 Run tests on ubuntu latest
  .github/workflows/CI.yml
Labels: tests

#1322 Handle user clicking on child element of list item
  www/js/app.js
Labels: backend, user interface, remove-jquery, bug-non-critical

#1324 Attempt fixes for legacy Ray Charles test on Firefox for linux-latest
  .mocharc.json
  TESTS.md
  package-lock.json
  package.json
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  tests/unit/index.html
  www/index.html
Labels: bug, tests

#1321 Fix: making kiwix search result screenreader accessible #778
  www/index.html
  www/js/app.js
Labels: user interface, accessibility

#1328 Update code checking actions
  .github/workflows/CI.yml
  .github/workflows/codeql-analysis.yml
  CONTRIBUTING.md
  eslint.config.js
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  package-lock.json
  package.json
  rollup.config.js
  service-worker.js
  tests/e2e/runners/chrome/chrome58.bs.runner.js
  tests/e2e/runners/chrome/chrome60.bs.runner.js
  tests/e2e/runners/chrome/chromium.e2e.runner.js
  tests/e2e/runners/edge/edge18.bs.runner.js
  tests/e2e/runners/edge/ieMode.e2e.runner.js
  tests/e2e/runners/edge/microsoftEdge.e2e.runner.js
  tests/e2e/runners/firefox/firefox.e2e.runner.js
  tests/e2e/runners/firefox/firefox56.bs.runner.js
  tests/e2e/runners/firefox/firefox70.bs.runner.js
  tests/e2e/runners/safari/safari14.bs.runner.js
  tests/e2e/spec/gutenberg_ro.e2e.spec.js
  tests/e2e/spec/legacy-ray_charles.e2e.spec.js
  tests/e2e/spec/tonedear.e2e.spec.js
  tests/unit/js/init.js
  tests/unit/setup.js
  tests/unit/spec/mocha.test.js
  www/js/app.js
  www/js/init.js
  www/js/lib/abstractFilesystemAccess.js
  www/js/lib/cache.js
  www/js/lib/kiwixLibrary.js
  www/js/lib/popovers.js
  www/js/lib/settingsStore.js
  www/js/lib/uiUtil.js
  www/js/lib/utf8.js
  www/js/lib/util.js
  www/js/lib/zimArchive.js
Labels: cleanup, dependencies, tests
