Repository kiwix/kiwix-js, pull requests merged in 2025-04, with the labels that each got.

#1327 fix: show selected file in dropdown on refresh
  i18n/en.jsonp.js
  i18n/es.jsonp.js
  i18n/fr.jsonp.js
  www/index.html
  www/js/lib/abstractFilesystemAccess.js
Labels: user interface, bug-non-critical

#1329 Fixed Dropdown Dark mode UI and Searchbar Results Placement
  www/css/app.css
Labels: user interface, accessibility

#1338 Build compact code by default
  babel.config.js
  rollup.config.js
Labels: dependencies, build

#1339 Fixed the folder dark mode style
  www/css/app.css
Labels: regression, user interface, bug-non-critical

#1343 Update GH release action to Ubuntu 22.04
  .github/workflows/Release.yml
Labels: dependencies, build, task
